/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bodycyber;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author Mustafa
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    private  double count = 0, count1 = 0, count2 = 0, count3 = 0, count4 = 0;
    double total, total1, total2, total3, total4;
    Timer TimerA = new Timer("Display Timer");

    public HomePage() {
        initComponents();
    }
    
    TimerTask taskTime = new TimerTask() {

        @Override
        public void run() {

            Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("E dd/mm/yyyy hh:mm:ss a");
            timeNow.setText(sdf.format(date));
        }
    };

    TimerTask task = new TimerTask() {

        @Override
        public void run() {

            if (Startps1.getText().equals("Stop")) {
                count++;
                total = count;
            } else {
                count=0;
            }

            //To change body of generated methods, choose Tools | Templates.
        }
    };
    
    

    TimerTask task1 = new TimerTask() {

        @Override
        public void run() {
            if (StartPs2.getText().equals("Stop")) {
                count1++;
                total1 = count1;
            } else {
                count1 = 0;
            }

            //To change body of generated methods, choose Tools | Templates.
        }
    };
    TimerTask task2 = new TimerTask() {

        @Override
        public void run() {
            if (StartPs3.getText().equals("Stop")) {
                count2++;
                total2 = count2;
            } else {
                count2 = 0;
            }

            //To change body of generated methods, choose Tools | Templates.
        }
    };
    TimerTask task3 = new TimerTask() {

        @Override
        public void run() {
            if (StartPs4.getText().equals("Stop")) {
                count3++;
                total3 = count3;
            } else {
                count3 = 0;
            }

            //To change body of generated methods, choose Tools | Templates.
        }
    };
    TimerTask task4 = new TimerTask() {

        @Override
        public void run() {
            if (StartPs5.getText().equals("Stop")) {
                count4++;
                total4 = count4;
            } else {
                count4 = 0;
            }

            //To change body of generated methods, choose Tools | Templates.
        }
    };
    Color myGreen = new Color(0, 153, 51);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Startps1 = new javax.swing.JButton();
        StartPs2 = new javax.swing.JButton();
        timeNow = new javax.swing.JLabel();
        TimePs1 = new javax.swing.JTextField();
        TimePs2 = new javax.swing.JTextField();
        endps1 = new javax.swing.JTextField();
        endps2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CalcPs1 = new javax.swing.JButton();
        totalPs1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CalcPs2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        totalps3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        calcPs3 = new javax.swing.JButton();
        StartPs3 = new javax.swing.JToggleButton();
        TimePs3 = new javax.swing.JTextField();
        EndPs3 = new javax.swing.JTextField();
        totalps2 = new javax.swing.JTextField();
        StartPs4 = new javax.swing.JToggleButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        calcPs4 = new javax.swing.JButton();
        TimePs4 = new javax.swing.JTextField();
        EndPs4 = new javax.swing.JTextField();
        totalps4 = new javax.swing.JTextField();
        StartPs5 = new javax.swing.JToggleButton();
        Timeps5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        endPs5 = new javax.swing.JTextField();
        calcPs5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        totalps5 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DrinksPs2 = new javax.swing.JTextField();
        DrinksPs3 = new javax.swing.JTextField();
        DrinksPs4 = new javax.swing.JTextField();
        DrinksPs5 = new javax.swing.JTextField();
        DrinksPs1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        SinglePs1 = new javax.swing.JCheckBox();
        MultiPs1 = new javax.swing.JCheckBox();
        SinglePs2 = new javax.swing.JCheckBox();
        MultiPs2 = new javax.swing.JCheckBox();
        SinglePs3 = new javax.swing.JCheckBox();
        MultiPs3 = new javax.swing.JCheckBox();
        SinglePs4 = new javax.swing.JCheckBox();
        MultiPs4 = new javax.swing.JCheckBox();
        SinglePs5 = new javax.swing.JCheckBox();
        MultiPs5 = new javax.swing.JCheckBox();
        StatusPs1 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        StatusPs2 = new javax.swing.JLabel();
        StatusPs3 = new javax.swing.JLabel();
        StatusPs5 = new javax.swing.JLabel();
        StatusPs4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Courier New", 3, 35)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" Playstation Cyber");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Startps1.setBackground(new java.awt.Color(102, 102, 255));
        Startps1.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        Startps1.setForeground(new java.awt.Color(255, 255, 255));
        Startps1.setText("Start");
        Startps1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Startps1ActionPerformed(evt);
            }
        });

        StartPs2.setBackground(new java.awt.Color(102, 102, 255));
        StartPs2.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        StartPs2.setForeground(new java.awt.Color(255, 255, 255));
        StartPs2.setText("Start");
        StartPs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartPs2ActionPerformed(evt);
            }
        });

        timeNow.setFont(new java.awt.Font("Courier New", 3, 30)); // NOI18N
        timeNow.setForeground(new java.awt.Color(255, 255, 255));
        timeNow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        TimePs1.setEditable(false);
        TimePs1.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 12)); // NOI18N
        TimePs1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        TimePs2.setEditable(false);
        TimePs2.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 12)); // NOI18N
        TimePs2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        endps1.setEditable(false);
        endps1.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 12)); // NOI18N
        endps1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        endps2.setEditable(false);
        endps2.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 12)); // NOI18N
        endps2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ps1");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("startTime");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EndTime");

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ps2");

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("EndTime");

        CalcPs1.setBackground(new java.awt.Color(102, 102, 255));
        CalcPs1.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        CalcPs1.setForeground(new java.awt.Color(255, 255, 255));
        CalcPs1.setText("Calculate");
        CalcPs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcPs1ActionPerformed(evt);
            }
        });

        totalPs1.setEditable(false);
        totalPs1.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        totalPs1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalPs1.setText("0");

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total");

        CalcPs2.setBackground(new java.awt.Color(102, 102, 255));
        CalcPs2.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        CalcPs2.setForeground(new java.awt.Color(255, 255, 255));
        CalcPs2.setText("Calculate");
        CalcPs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcPs2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total");

        totalps3.setEditable(false);
        totalps3.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        totalps3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalps3.setText("0");

        jLabel12.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("EndTime");

        jLabel13.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Total");

        calcPs3.setBackground(new java.awt.Color(102, 102, 255));
        calcPs3.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        calcPs3.setForeground(new java.awt.Color(255, 255, 255));
        calcPs3.setText("Calculate");
        calcPs3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcPs3ActionPerformed(evt);
            }
        });

        StartPs3.setBackground(new java.awt.Color(102, 102, 255));
        StartPs3.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        StartPs3.setForeground(new java.awt.Color(255, 255, 255));
        StartPs3.setText("Start");
        StartPs3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartPs3ActionPerformed(evt);
            }
        });

        TimePs3.setEditable(false);
        TimePs3.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 12)); // NOI18N
        TimePs3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        EndPs3.setEditable(false);
        EndPs3.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 12)); // NOI18N
        EndPs3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EndPs3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndPs3ActionPerformed(evt);
            }
        });

        totalps2.setEditable(false);
        totalps2.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        totalps2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalps2.setText("0");

        StartPs4.setBackground(new java.awt.Color(102, 102, 255));
        StartPs4.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        StartPs4.setForeground(new java.awt.Color(255, 255, 255));
        StartPs4.setText("Start");
        StartPs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartPs4ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("EndTime");

        jLabel17.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Total");

        calcPs4.setBackground(new java.awt.Color(102, 102, 255));
        calcPs4.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        calcPs4.setForeground(new java.awt.Color(255, 255, 255));
        calcPs4.setText("Calculate");
        calcPs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcPs4ActionPerformed(evt);
            }
        });

        TimePs4.setEditable(false);
        TimePs4.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 12)); // NOI18N
        TimePs4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        EndPs4.setEditable(false);
        EndPs4.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 12)); // NOI18N
        EndPs4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EndPs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndPs4ActionPerformed(evt);
            }
        });

        totalps4.setEditable(false);
        totalps4.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        totalps4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalps4.setText("0");

        StartPs5.setBackground(new java.awt.Color(102, 102, 255));
        StartPs5.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        StartPs5.setForeground(new java.awt.Color(255, 255, 255));
        StartPs5.setText("Start");
        StartPs5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartPs5ActionPerformed(evt);
            }
        });

        Timeps5.setEditable(false);
        Timeps5.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 12)); // NOI18N
        Timeps5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Timeps5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Timeps5ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("EndTime");

        endPs5.setEditable(false);
        endPs5.setFont(new java.awt.Font("Microsoft Sans Serif", 3, 12)); // NOI18N
        endPs5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        endPs5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endPs5ActionPerformed(evt);
            }
        });

        calcPs5.setBackground(new java.awt.Color(102, 102, 255));
        calcPs5.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        calcPs5.setForeground(new java.awt.Color(255, 255, 255));
        calcPs5.setText("Calculate");
        calcPs5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcPs5ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Total");

        totalps5.setEditable(false);
        totalps5.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        totalps5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalps5.setText("0");

        jLabel22.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ps3");

        jLabel23.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("ps4");

        jLabel24.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("ps5");

        jLabel10.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("startTime");

        jLabel14.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("startTime");

        jLabel18.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("startTime");

        jLabel11.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("startTime");

        DrinksPs2.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        DrinksPs2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DrinksPs2.setText("0");

        DrinksPs3.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        DrinksPs3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DrinksPs3.setText("0");

        DrinksPs4.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        DrinksPs4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DrinksPs4.setText("0");

        DrinksPs5.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        DrinksPs5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DrinksPs5.setText("0");

        DrinksPs1.setFont(new java.awt.Font("Courier New", 3, 14)); // NOI18N
        DrinksPs1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DrinksPs1.setText("0");

        jLabel15.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Drinks");

        jLabel19.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Option");

        SinglePs1.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        SinglePs1.setForeground(new java.awt.Color(255, 255, 255));
        SinglePs1.setText("Single");

        MultiPs1.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        MultiPs1.setForeground(new java.awt.Color(255, 255, 255));
        MultiPs1.setText("Multi");

        SinglePs2.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        SinglePs2.setForeground(new java.awt.Color(255, 255, 255));
        SinglePs2.setText("Single");

        MultiPs2.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        MultiPs2.setForeground(new java.awt.Color(255, 255, 255));
        MultiPs2.setText("Multi");

        SinglePs3.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        SinglePs3.setForeground(new java.awt.Color(255, 255, 255));
        SinglePs3.setText("Single");

        MultiPs3.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        MultiPs3.setForeground(new java.awt.Color(255, 255, 255));
        MultiPs3.setText("Multi");

        SinglePs4.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        SinglePs4.setForeground(new java.awt.Color(255, 255, 255));
        SinglePs4.setText("Single");

        MultiPs4.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        MultiPs4.setForeground(new java.awt.Color(255, 255, 255));
        MultiPs4.setText("Multi");

        SinglePs5.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        SinglePs5.setForeground(new java.awt.Color(255, 255, 255));
        SinglePs5.setText("Single");

        MultiPs5.setFont(new java.awt.Font("Courier New", 1, 16)); // NOI18N
        MultiPs5.setForeground(new java.awt.Color(255, 255, 255));
        MultiPs5.setText("Multi");

        StatusPs1.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        StatusPs1.setForeground(new java.awt.Color(0, 153, 51));
        StatusPs1.setText("Ready");

        jLabel26.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Status");

        StatusPs2.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        StatusPs2.setForeground(new java.awt.Color(0, 153, 51));
        StatusPs2.setText("Ready");

        StatusPs3.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        StatusPs3.setForeground(new java.awt.Color(0, 153, 0));
        StatusPs3.setText("Ready");

        StatusPs5.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        StatusPs5.setForeground(new java.awt.Color(0, 153, 0));
        StatusPs5.setText("Ready");

        StatusPs4.setFont(new java.awt.Font("Courier New", 1, 20)); // NOI18N
        StatusPs4.setForeground(new java.awt.Color(0, 153, 0));
        StatusPs4.setText("Ready");

        jLabel6.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel7))
            .addGroup(layout.createSequentialGroup()
                .addGap(1246, 1246, 1246)
                .addComponent(StatusPs5))
            .addGroup(layout.createSequentialGroup()
                .addGap(579, 579, 579)
                .addComponent(jLabel10))
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel9))
            .addGroup(layout.createSequentialGroup()
                .addGap(977, 977, 977)
                .addComponent(TimePs4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1130, 1130, 1130)
                .addComponent(jLabel20))
            .addGroup(layout.createSequentialGroup()
                .addGap(1178, 1178, 1178)
                .addComponent(jLabel24))
            .addGroup(layout.createSequentialGroup()
                .addGap(1106, 1106, 1106)
                .addComponent(jLabel14))
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(CalcPs1))
            .addGroup(layout.createSequentialGroup()
                .addGap(1272, 1272, 1272)
                .addComponent(totalps5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(824, 824, 824)
                .addComponent(timeNow, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(994, 994, 994)
                .addComponent(StatusPs4))
            .addGroup(layout.createSequentialGroup()
                .addGap(651, 651, 651)
                .addComponent(jLabel22))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(SinglePs1))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(MultiPs1))
            .addGroup(layout.createSequentialGroup()
                .addGap(977, 977, 977)
                .addComponent(SinglePs4))
            .addGroup(layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(MultiPs2))
            .addGroup(layout.createSequentialGroup()
                .addGap(885, 885, 885)
                .addComponent(jLabel16))
            .addGroup(layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(1002, 1002, 1002)
                .addComponent(DrinksPs4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addComponent(totalps2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(638, 638, 638)
                .addComponent(calcPs3))
            .addGroup(layout.createSequentialGroup()
                .addGap(445, 445, 445)
                .addComponent(StatusPs2))
            .addGroup(layout.createSequentialGroup()
                .addGap(711, 711, 711)
                .addComponent(totalps3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(885, 885, 885)
                .addComponent(jLabel17))
            .addGroup(layout.createSequentialGroup()
                .addGap(724, 724, 724)
                .addComponent(SinglePs3))
            .addGroup(layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(CalcPs2))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(Startps1))
            .addGroup(layout.createSequentialGroup()
                .addGap(724, 724, 724)
                .addComponent(MultiPs3))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(totalPs1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(977, 977, 977)
                .addComponent(EndPs4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(603, 603, 603)
                .addComponent(jLabel12))
            .addGroup(layout.createSequentialGroup()
                .addGap(603, 603, 603)
                .addComponent(jLabel13))
            .addGroup(layout.createSequentialGroup()
                .addGap(451, 451, 451)
                .addComponent(DrinksPs2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(SinglePs2))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(1237, 1237, 1237)
                .addComponent(endPs5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(940, 940, 940)
                .addComponent(calcPs4))
            .addGroup(layout.createSequentialGroup()
                .addGap(711, 711, 711)
                .addComponent(DrinksPs3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(724, 724, 724)
                .addComponent(StartPs3))
            .addGroup(layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(TimePs2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1237, 1237, 1237)
                .addComponent(SinglePs5))
            .addGroup(layout.createSequentialGroup()
                .addGap(724, 724, 724)
                .addComponent(TimePs3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel19))
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(StatusPs1))
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(DrinksPs1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1237, 1237, 1237)
                .addComponent(MultiPs5))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel26))
            .addGroup(layout.createSequentialGroup()
                .addGap(891, 891, 891)
                .addComponent(jLabel23))
            .addGroup(layout.createSequentialGroup()
                .addGap(724, 724, 724)
                .addComponent(EndPs3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(TimePs1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1237, 1237, 1237)
                .addComponent(StartPs5))
            .addGroup(layout.createSequentialGroup()
                .addGap(1272, 1272, 1272)
                .addComponent(DrinksPs5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel8))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel15))
            .addGroup(layout.createSequentialGroup()
                .addGap(299, 299, 299)
                .addComponent(jLabel11))
            .addGroup(layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(endps2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(977, 977, 977)
                .addComponent(StartPs4))
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(1237, 1237, 1237)
                .addComponent(Timeps5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(1173, 1173, 1173)
                .addComponent(jLabel21))
            .addGroup(layout.createSequentialGroup()
                .addGap(1011, 1011, 1011)
                .addComponent(totalps4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(436, 436, 436)
                .addComponent(StartPs2))
            .addGroup(layout.createSequentialGroup()
                .addGap(977, 977, 977)
                .addComponent(MultiPs4))
            .addGroup(layout.createSequentialGroup()
                .addGap(843, 843, 843)
                .addComponent(jLabel18))
            .addGroup(layout.createSequentialGroup()
                .addGap(1200, 1200, 1200)
                .addComponent(calcPs5))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(endps1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(736, 736, 736)
                .addComponent(StatusPs3))
            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(StatusPs5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(532, 532, 532)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(TimePs4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel20))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel14))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(CalcPs1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(532, 532, 532)
                        .addComponent(totalps5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(timeNow, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(StatusPs4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(SinglePs1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(MultiPs1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(SinglePs4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(MultiPs2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(DrinksPs4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addComponent(totalps2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(calcPs3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(StatusPs2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addComponent(totalps3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(530, 530, 530)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(SinglePs3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(CalcPs2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(Startps1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(MultiPs3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(534, 534, 534)
                        .addComponent(totalPs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(EndPs4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(532, 532, 532)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(DrinksPs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(SinglePs2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(endPs5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(calcPs4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(DrinksPs3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(StartPs3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(TimePs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(SinglePs5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(TimePs3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(StatusPs1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(DrinksPs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(MultiPs5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(EndPs3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(TimePs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(StartPs5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(DrinksPs5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(532, 532, 532)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(405, 405, 405)
                        .addComponent(jLabel15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(endps2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(StartPs4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(Timeps5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(530, 530, 530)
                        .addComponent(jLabel21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(532, 532, 532)
                        .addComponent(totalps4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(StartPs2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(MultiPs4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(470, 470, 470)
                        .addComponent(calcPs5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(endps1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(StatusPs3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    long ps1Start, ps1Stop;
    private void CalcPs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcPs1ActionPerformed
        if (StatusPs1.getText().equals("Ready")) {
            
            if (SinglePs1.isSelected()) {
                total = (total/60)*(0.25);
                total += (Integer.parseInt(DrinksPs1.getText()) * 5);
                totalPs1.setText(Math.floor(total) + "");
                total=0;
            } else if (MultiPs1.isSelected()) {
                total = (total/60)*(0.33333333);
                total += (Integer.parseInt(DrinksPs1.getText()) * 5);
                totalPs1.setText(Math.floor(total) + "");
                total=0;
            } else {
            } 
        }
    }//GEN-LAST:event_CalcPs1ActionPerformed

    private void CalcPs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcPs2ActionPerformed
        if (StatusPs2.getText().equals("Ready")) {
            if (SinglePs2.isSelected()) {
                total1 = (total1 / 60) * (0.25);
                total1 += (Integer.parseInt(DrinksPs2.getText()) * 5);
                totalps2.setText(Math.floor(total1) + "");
                total1=0;
            } else if (MultiPs2.isSelected()) {
                total1 = (total1 / 60) * (0.33333333);
                total1 += (Integer.parseInt(DrinksPs2.getText()) * 5);
                totalps2.setText(Math.floor(total1) + "");
                total1=0;
            } else {
            }
            
        }
    }//GEN-LAST:event_CalcPs2ActionPerformed

    private void EndPs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndPs3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EndPs3ActionPerformed

    private void EndPs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndPs4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EndPs4ActionPerformed

    private void endPs5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endPs5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endPs5ActionPerformed

    private void Timeps5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Timeps5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Timeps5ActionPerformed

    private void StartPs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartPs3ActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
        if (StartPs3.getText().equals("Start")) {
            StartPs3.setText("Stop");
            StatusPs3.setText("Busy");
            StatusPs3.setForeground(Color.RED);
            ps1Start = System.currentTimeMillis();
            totalps3.setText("0");
            TimePs3.setText(sdf.format(ps1Start));
            EndPs3.setText("");
            try {
                TimerA.scheduleAtFixedRate(task2, 1000, 1000);
            } catch (Exception e) {
            }
        } else {
            StartPs3.setText("Start");
            ps1Stop = System.currentTimeMillis();
            StatusPs3.setText("Ready");
            StatusPs3.setForeground(Color.getColor(null, myGreen));
            EndPs3.setText(sdf.format(ps1Stop));

        }
    }//GEN-LAST:event_StartPs3ActionPerformed

    private void calcPs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcPs3ActionPerformed
        if (StatusPs3.getText().equals("Ready")) {
            
            if (SinglePs3.isSelected()) {
                total2 = (total2 / 60) * (0.25);
                total2 += (Integer.parseInt(DrinksPs3.getText()) * 5);
                totalps3.setText(Math.floor(total2) + "");
                total2=0;
            } else if (MultiPs3.isSelected()) {
                total2 = (total2 / 60) * (0.33333333);
                total2 += (Integer.parseInt(DrinksPs3.getText()) * 5);
                totalps3.setText(Math.floor(total2) + "");
                total2=0;
            } else {
            }
            
        }
    }//GEN-LAST:event_calcPs3ActionPerformed

    private void StartPs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartPs4ActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
        if (StartPs4.getText().equals("Start")) {
            StartPs4.setText("Stop");
            StatusPs4.setText("Busy");
            StatusPs4.setForeground(Color.RED);
            ps1Start = System.currentTimeMillis();
            totalps4.setText("0");
            TimePs4.setText(sdf.format(ps1Start));
            EndPs4.setText("");
            try {
                TimerA.scheduleAtFixedRate(task3, 1000, 1000);
            } catch (Exception e) {
            }
        } else {
            StartPs4.setText("Start");
            ps1Stop = System.currentTimeMillis();
            StatusPs4.setText("Ready");
            StatusPs4.setForeground(Color.getColor(null, myGreen));
            EndPs4.setText(sdf.format(ps1Stop));

        }
    }//GEN-LAST:event_StartPs4ActionPerformed

    private void StartPs5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartPs5ActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
        if (StartPs5.getText().equals("Start")) {
            StartPs5.setText("Stop");
            StatusPs5.setText("Busy");
            StatusPs5.setForeground(Color.RED);
            ps1Start = System.currentTimeMillis();
            totalps5.setText("0");
            Timeps5.setText(sdf.format(ps1Start));
            endPs5.setText("");
            try {
                TimerA.scheduleAtFixedRate(task4, 1000, 1000);
            } catch (Exception e) {
            }
        } else {
            StartPs5.setText("Start");
            ps1Stop = System.currentTimeMillis();
            StatusPs5.setText("Ready");
            StatusPs5.setForeground(Color.getColor(null, myGreen));
            endPs5.setText(sdf.format(ps1Stop));

        }
    }//GEN-LAST:event_StartPs5ActionPerformed

    private void calcPs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcPs4ActionPerformed
        if (StatusPs4.getText().equals("Ready")) {
            if (SinglePs4.isSelected()) {
                total3 = (total3/60) * (0.16666667);
                total3 += (Integer.parseInt(DrinksPs4.getText()) * 5);
                totalps4.setText(Math.floor(total3) + "");
                total3=0;
            } else if (MultiPs4.isSelected()) {
                total3 = (total3/60) * (0.25);
                total3 += (Integer.parseInt(DrinksPs4.getText()) * 5);
                totalps4.setText(Math.floor(total3) + "");
                total3=0;
            } else {
            }
        }
    }//GEN-LAST:event_calcPs4ActionPerformed

    private void calcPs5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcPs5ActionPerformed
        if (StatusPs5.getText().equals("Ready")) {
            if (SinglePs5.isSelected()) {
                total4 = (total4 / 60) * (0.33333333);
                total4 += (Integer.parseInt(DrinksPs5.getText()) * 5);
                totalps5.setText(Math.floor(total4) + "");
                total4=0;
            } else if (MultiPs5.isSelected()) {
                total4 = (total4 / 60) * (0.41666667);
                total4 += (Integer.parseInt(DrinksPs5.getText()) * 5);
                totalps5.setText(Math.floor(total4) + "");
                total4=0;
            } else {
            }
        }
    }//GEN-LAST:event_calcPs5ActionPerformed

    private void StartPs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartPs2ActionPerformed
SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
        if (StartPs2.getText().equals("Start")) {
            StartPs2.setText("Stop");
            StatusPs2.setText("Busy");
            StatusPs2.setForeground(Color.RED);
            ps1Start = System.currentTimeMillis();
            totalps2.setText("0");
            TimePs2.setText(sdf.format(ps1Start));
            endps2.setText("");
            try {
                TimerA.scheduleAtFixedRate(task1, 1000, 1000);
            } catch (Exception e) {
            }
        } else {
            StartPs2.setText("Start");
            ps1Stop = System.currentTimeMillis();
            StatusPs2.setText("Ready");
            StatusPs2.setForeground(Color.getColor(null, myGreen));
            endps2.setText(sdf.format(ps1Stop));

        }
    }//GEN-LAST:event_StartPs2ActionPerformed

    private void Startps1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Startps1ActionPerformed
SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss");
        if (Startps1.getText().equals("Start")) {
            Startps1.setText("Stop");
            StatusPs1.setText("Busy");
            StatusPs1.setForeground(Color.RED);
            ps1Start = System.currentTimeMillis();
            totalPs1.setText("0");
            TimePs1.setText(sdf.format(ps1Start));
            endps1.setText("");
            try {
                TimerA.scheduleAtFixedRate(task, 1000, 1000);
            } catch (Exception e) {
            }
        } else {
            Startps1.setText("Start");
            StatusPs1.setText("Ready");
            StatusPs1.setForeground(Color.getColor(null, myGreen));
            ps1Stop = System.currentTimeMillis();
            endps1.setText(sdf.format(ps1Stop));

        }
    }//GEN-LAST:event_Startps1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try{
            TimerA.scheduleAtFixedRate(taskTime, 1000, 1000);
        }catch(Exception e){}
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcPs1;
    private javax.swing.JButton CalcPs2;
    private javax.swing.JTextField DrinksPs1;
    private javax.swing.JTextField DrinksPs2;
    private javax.swing.JTextField DrinksPs3;
    private javax.swing.JTextField DrinksPs4;
    private javax.swing.JTextField DrinksPs5;
    private javax.swing.JTextField EndPs3;
    private javax.swing.JTextField EndPs4;
    private javax.swing.JCheckBox MultiPs1;
    private javax.swing.JCheckBox MultiPs2;
    private javax.swing.JCheckBox MultiPs3;
    private javax.swing.JCheckBox MultiPs4;
    private javax.swing.JCheckBox MultiPs5;
    private javax.swing.JCheckBox SinglePs1;
    private javax.swing.JCheckBox SinglePs2;
    private javax.swing.JCheckBox SinglePs3;
    private javax.swing.JCheckBox SinglePs4;
    private javax.swing.JCheckBox SinglePs5;
    private javax.swing.JButton StartPs2;
    private javax.swing.JToggleButton StartPs3;
    private javax.swing.JToggleButton StartPs4;
    private javax.swing.JToggleButton StartPs5;
    private javax.swing.JButton Startps1;
    private javax.swing.JLabel StatusPs1;
    private javax.swing.JLabel StatusPs2;
    private javax.swing.JLabel StatusPs3;
    private javax.swing.JLabel StatusPs4;
    private javax.swing.JLabel StatusPs5;
    private javax.swing.JTextField TimePs1;
    private javax.swing.JTextField TimePs2;
    private javax.swing.JTextField TimePs3;
    private javax.swing.JTextField TimePs4;
    private javax.swing.JTextField Timeps5;
    private javax.swing.JButton calcPs3;
    private javax.swing.JButton calcPs4;
    private javax.swing.JButton calcPs5;
    private javax.swing.JTextField endPs5;
    private javax.swing.JTextField endps1;
    private javax.swing.JTextField endps2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel timeNow;
    private javax.swing.JTextField totalPs1;
    private javax.swing.JTextField totalps2;
    private javax.swing.JTextField totalps3;
    private javax.swing.JTextField totalps4;
    private javax.swing.JTextField totalps5;
    // End of variables declaration//GEN-END:variables
}
